"use client";

import { useMemo, useState } from "react";

type Position = [number, number];
type Feature = { type: "Feature"; properties?: Record<string, unknown>; geometry?: { type?: string; coordinates?: unknown } };
const palette = ["#215e59", "#3e9c81", "#e3c660", "#e88b48", "#cc4f37"];
function rings(feature: Feature): Position[][] { const geometry = feature.geometry; if (!geometry?.coordinates) return []; if (geometry.type === "Polygon") return geometry.coordinates as Position[][]; if (geometry.type === "MultiPolygon") return (geometry.coordinates as Position[][][]).flat(); return []; }
function providerTileValue(properties: Record<string, unknown> | undefined): number | null { if (!properties) return null; const entry = Object.entries(properties).find(([key, value]) => /temperature|tcm|value/i.test(key) && typeof value === "number"); return entry ? entry[1] as number : null; }

export function HeatmapCanvas({ mapData, statsData }: { mapData: Record<string, unknown>; statsData: Record<string, unknown> | null }) {
  const features = (Array.isArray(mapData.features) ? mapData.features : []) as Feature[]; const [selected, setSelected] = useState<Feature | null>(null);
  const points = useMemo(() => features.flatMap(rings).flat(), [features]); const values = useMemo(() => features.map(item => providerTileValue(item.properties)).filter((item): item is number => item !== null), [features]);
  const bounds = useMemo(() => { const longs = points.map(point => point[0]); const lats = points.map(point => point[1]); return { minLon: Math.min(...longs), maxLon: Math.max(...longs), minLat: Math.min(...lats), maxLat: Math.max(...lats) }; }, [points]);
  const project = (point: Position) => { const width = Math.max(bounds.maxLon - bounds.minLon, 0.00001); const height = Math.max(bounds.maxLat - bounds.minLat, 0.00001); return `${((point[0] - bounds.minLon) / width) * 100},${100 - ((point[1] - bounds.minLat) / height) * 100}`; };
  const color = (value: number | null) => { if (value === null || values.length === 0) return "#a8c9be"; const min = Math.min(...values); const max = Math.max(...values); const index = Math.min(palette.length - 1, Math.floor(((value - min) / Math.max(max - min, 0.00001)) * palette.length)); return palette[index]; };
  if (!points.length) return <div className="rounded-2xl bg-sand p-5 text-sm text-ink/60">FortyGuard returned map features without drawable polygon geometry.</div>;
  return <div className="grid gap-5 lg:grid-cols-[1.45fr_.55fr]"><div><div className="relative overflow-hidden rounded-2xl bg-[#dfece7] shadow-inner"><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Interactive FortyGuard heatmap tiles" className="aspect-square w-full"><rect width="100" height="100" fill="#e9f2ed" />{features.flatMap((feature, featureIndex) => rings(feature).map((ring, ringIndex) => <polygon key={`${featureIndex}-${ringIndex}`} points={ring.map(project).join(" ")} fill={color(providerTileValue(feature.properties))} stroke="rgba(255,255,255,.85)" strokeWidth=".28" vectorEffect="non-scaling-stroke" className="cursor-pointer transition-opacity hover:opacity-75" onClick={() => setSelected(feature)} />))}</svg><span className="absolute left-3 top-3 rounded-full bg-white/90 px-3 py-1 text-xs font-semibold text-ink">{features.length} real provider tiles</span></div><div className="mt-3 flex items-center justify-between text-xs text-ink/55"><span>Cooler relative tile values</span><div className="h-2 w-28 rounded-full" style={{ background: "linear-gradient(90deg, #215e59, #3e9c81, #e3c660, #e88b48, #cc4f37)" }} /><span>Hotter relative tile values</span></div>{values.length === 0 && <p className="mt-2 text-xs text-ink/55">FortyGuard did not expose a recognized numeric tile value in this response, so tiles are shown in a neutral color. Select one to inspect its raw provider properties.</p>}</div><aside className="rounded-2xl bg-sand p-4"><p className="text-xs font-semibold uppercase tracking-wide text-moss">SELECTED MAP AREA</p>{selected ? <pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap text-xs leading-5 text-ink/70">{JSON.stringify(selected.properties ?? {}, null, 2)}</pre> : <p className="mt-3 text-sm leading-6 text-ink/60">Select a heatmap tile to see the environmental values FortyGuard returned for that area.</p>}<p className="mt-5 text-xs font-semibold uppercase tracking-wide text-moss">MAP STATISTICS</p><pre className="mt-2 max-h-40 overflow-auto whitespace-pre-wrap text-xs leading-5 text-ink/60">{JSON.stringify(statsData ?? {}, null, 2)}</pre></aside></div>;
}
