"use client";

import { FormEvent, useState } from "react";

import { request } from "../lib/api";
import { LocationPicker } from "./location-picker";

type Reply = { answer: string; used_current_conditions: boolean; context_note: string; disclaimer: string; timings_ms: Record<string, number> };

export function SafetyAssistant() {
  const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [reply, setReply] = useState<Reply | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [stage, setStage] = useState(""); const [latitude, setLatitude] = useState(""); const [longitude, setLongitude] = useState("");
  async function ask(event: FormEvent) { event.preventDefault(); if (!message.trim()) return; setBusy(true); setError(""); setReply(null); setStage(latitude && longitude ? "Collecting current FortyGuard conditions and checking PawGuard safety limits…" : "Checking saved PawGuard safety context…"); try { window.setTimeout(() => setStage("Preparing grounded guidance from PawGuard’s safety rules…"), 1200); setReply(await request<Reply>("/assistant/chat", { method: "POST", timeoutMs: 65_000, body: JSON.stringify({ message, latitude: latitude ? Number(latitude) : null, longitude: longitude ? Number(longitude) : null }) })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Assistant is unavailable."); } finally { setBusy(false); setStage(""); } }
  return <><button onClick={() => setOpen(true)} className="fixed bottom-5 right-5 z-20 rounded-full bg-moss px-5 py-3 text-sm font-bold text-white shadow-card">Ask PawGuard</button>{open && <div className="fixed inset-0 z-40 flex items-end bg-ink/35 p-4 sm:items-center sm:justify-end"><section className="w-full max-w-md rounded-3xl bg-white p-6 shadow-card"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-moss">AI SAFETY ASSISTANT</p><h2 className="mt-1 text-xl font-bold">Grounded in PawGuard</h2></div><button onClick={() => setOpen(false)} className="rounded-lg px-2 py-1 text-ink/60">✕</button></div><p className="mt-3 text-sm leading-6 text-ink/60">Add your location for a live FortyGuard-based answer. If live data is delayed, PawGuard gives profile-based guidance without inventing conditions.</p><form onSubmit={ask} className="mt-4"><LocationPicker compact required={false} latitude={latitude} longitude={longitude} onChange={(lat, lon) => { setLatitude(lat); setLongitude(lon); }} /><textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Can I walk Max now?" maxLength={1200} className="mt-3 min-h-24 w-full rounded-xl border border-ink/15 p-3 text-sm" /><button disabled={busy} className="mt-3 w-full rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Working safely…" : "Ask safely"}</button></form>{busy && <p className="mt-3 rounded-xl bg-mint/30 p-3 text-sm leading-6 text-ink/75">{stage}</p>}{error && <p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{reply && <article className="mt-4 rounded-2xl bg-mint/30 p-4"><p className="whitespace-pre-wrap text-sm leading-6 text-ink/80">{reply.answer}</p><p className="mt-3 text-xs leading-5 text-ink/55">{reply.used_current_conditions ? `${reply.context_note} ` : ""}{reply.disclaimer}</p></article>}</section></div>}</>;
}
